file_format: "1"
id: oak58
name: oak58
type: shield
url: https://github.com/nicholasoclassen/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - oak58_left
  - oak58_right
