file_format: "1"
id: lily58_oak
name: Lily58_oak
type: shield
url: https://github.com/nicholasoclassen/zmk-config/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - lily58_oak_left
  - lily58_oak_right
